<!--/**-->
<!--* @author    Tigren Solutions <info@tigren.com>-->
<!--* @copyright Copyright (c) 2023 Tigren Solutions <https://www.tigren.com>. All rights reserved.-->
<!--* @license   Open Software License ("OSL") v. 3.0-->
<!--*/-->

<style>
    .button {
        POSITION: relative;
        border-radius: 20px;
        border: 1px solid #4bb6b7;
        background-color: #4bb6b7;
        color: #fff;
        font-size: 15px;
        font-weight: 700;
        margin: 10px;
        padding: 10px 80px;
        letter-spacing: 1px;
        text-transform: capitalize;
        transition: 0.3s ease-in-out;
    }

    .button:hover {
        letter-spacing: 3px;
    }

    .buttom:active {
        transform: scale(0.95);
    }

    .button:focus {
        outline: none;
    }

    .button.ghost {
        background-color: rgba(255, 255, 255, 0.2);
        border: 2px solid #fff;
        color: #fff;
    }

    .button.ghost i {
        position: absolute;
        opacity: 0;
        transition: 0.3s ease-in-out;
    }

    .button.ghost i.register {
        right: 70px;
    }

    .button.ghost i.login {
        left: 30px;
    }

    .button.ghost:hover i.register {
        right: 40px;
        opacity: 1;
    }

    .button.ghost:hover i.login {
        left: 40px;
        opacity: 1;
    }

    .form {
        background-color: #fff;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        padding: 0 50px;
        height: 100%;
        text-align: center;
    }

    .input {
        background-color: #eee;
        border-radius: 10px;
        border: none;
        padding: 12px 15px;
        margin: 8px 0;
        width: 100%;
    }

    .containerform {
        background-color: #fff;
        border-radius: 25px;
        box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22);
        position: relative;
        overflow: hidden;
        width: 768px;
        max-width: 100%;
        min-height: 500px;
    }

    .form-container {
        position: absolute;
        top: 0;
        height: 100%;
        transition: all 0.6s ease-in-out;
    }

    .login-container {
        left: 0;
        width: 50%;
        z-index: 2;
    }

    .containerform.right-panel-active .login-container {
        transform: translateX(100%);
    }

    .register-container {
        left: 0;
        width: 50%;
        opacity: 0;
        z-index: 1;
    }

    .containerform.right-panel-active .register-container {
        transform: translateX(100%);
        opacity: 1;
        z-index: 5;
        animation: show 0.6s;
    }

    @keyframes show {
        0%,
        49.99% {
            opacity: 0;
            z-index: 1;
        }
        50%,
        100% {
            opacity: 1;
            z-index: 5;
        }
    }

    .overlay-container {
        position: absolute;
        top: 0;
        left: 50%;
        width: 50%;
        height: 100%;
        overflow: hidden;
        transition: transform 0.6s ease-in-out;
        z-index: 100;
    }

    .containerform.right-panel-active .overlay-container {
        transform: translateX(-100%);
    }

    .overlay {
        /* background: #4bb6b7;
        background: -webkit-linear-gradient(to right, #4bb6b7, #4bb6b7);
        background: linear-gradient(to right, #4bb6b7, #4bb6b7); */
        background-image: url("https://khoinguonsangtao.vn/wp-content/uploads/2022/10/anh-gif-buon-mot-minh-trong-dem.gif");
        background-repeat: no-repeat;
        background-size: cover;
        background-position: 0 0;
        color: #fff;
        position: relative;
        left: -100%;
        height: 100%;
        width: 200%;
        transform: translateX(0);
        transition: transform 0.6s ease-in-out;
    }

    .overlay::before {
        content: '';
        position: absolute;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: linear-gradient( to top, rgba(46, 94, 109, 0.4) 40%, rgba(46, 94, 109, 0));
    }

    .containerform.right-panel-active .overlay {
        transform: translateX(50%);
    }

    .overlay-panel {
        position: absolute;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        padding: 0 40px;
        text-align: center;
        top: 0;
        height: 100%;
        width: 50%;
        transform: translateX(0);
        transition: transform 0.6s ease-in-out;
    }

    .overlay-left {
        transform: translateX(-20%);
    }

    .containerform.right-panel-active .overlay-left {
        transform: translateX(0);
    }

    .overlay-right {
        right: 0;
        transform: translateX(0);
    }

    .containerform.right-panel-active .overlay-right {
        transform: translateX(20%);
    }

</style>



<br>
<br>
<br>
<div class="containerform" id="containerform" >
    <div class="form-container register-container">
        <form class="form" >
            <h1>Đăng ký</h1>
            <input class="input" type="text" placeholder="Name" name="name"/>
            <input class="input" type="text" placeholder="Phone" name="phone">
            <input class="input" type="email" placeholder="Email" name="email"/>
            <input class="input" type="password" placeholder="Password" name="password"/>
            <button class="button" >Đăng ký</button>
        </form>
    </div>

    <div class="form-container login-container">
        <form class="form" >
            <h1>Đăng nhập</h1>
            <input class="input" type="email" placeholder="Email" name="email"/>
            <input class="input" type="password" placeholder="Password" name="password"/>
            <button class="button" >Đăng nhập</button>
        </form>
    </div>
    <div class="overlay-container">
        <div class="overlay">
            <div class="overlay-panel overlay-left">
                <h1>Chào mừng quay trở lại!</h1>
                <p>Để giữ kết nối với chúng tôi, vui lòng đăng nhập bằng thông tin cá nhân của bạn</p>
                <button class="button ghost" id="login">Đăng nhập<i class="fa fa-sign-in"></i></button>
            </div>
            <div class="overlay-panel overlay-right">
                <h1>Xin chào, Bạn của tôi ơi!</h1>
                <p>Nhập thông tin cá nhân của bạn và bắt đầu hành trình với chúng tôi</p>
                <button class="button ghost" id="register">Đăng ký <i class="fa fa-sign-up"></i></button>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<br>
<script>
    const registerButton = document.getElementById('register');
    const loginButton = document.getElementById('login');
    const container = document.getElementById('containerform');
    registerButton.addEventListener('click', () => {
        container.classList.add('right-panel-active')
    });
    loginButton.addEventListener('click', () => {
        container.classList.remove('right-panel-active')
    });
</script>
